# -*- coding: utf-8 -*-
"""ml.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/sonjoy1s/dcadec83914fc1dc30c87b97626af4ee/ml.ipynb
"""

# problem solved
from functools import reduce
with open("./sample_data/sample.txt","r") as file:
  strings = file.readlines()
  total_lines = len(strings) # total line ber kora jonno
  # how much number of words : koto ghula words ache ta ber korbo
  numbers_of_word = list(map(lambda x : len(x.split()),strings))
  total_number_of_word = reduce(lambda x,y : x+y, numbers_of_word)
  # number of character ber kora lagbe
  strings = list(map(str.strip,strings)) # deleted \n line er jonno
  strings = list(map(lambda x : x.replace(" ",""),strings)) #space deleted korar jonno
  number_of_character = list(map(lambda x : len(x),strings))
  total_character = reduce(lambda x,y : x + y, number_of_character)
with open("./sample_data/counter_of_string.txt","w") as file :
  file.write(f"total line : {total_lines}\n")
  file.write(f"total word : {total_number_of_word}\n")
  file.write(f"total character : {total_character}")